legado/urls.py
from django.conf.urls import patterns,include,url
from django.contrib import admin
from legado import views

admin.autodiscover()
urlpatterns = patterns('legado.views',
                       (r'^ckeditor/', include('ckeditor_uploader.urls')),
                      # (r'^search/', include('haystack.urls')),
                   url(r'^$', 'Inicio', name='inicio'),
                   url(r'^search/autocomplete/', 'autocomplete', name='autocomplete'),
                   url(r'^somos/', 'SomosIndex', name='somos'),
                   url(r'^funciona/', 'FuncionaIndex', name='funciona'),
                   url(r'^preguntas/', 'PreguntasIndex', name='preguntas'),
                   url(r'^biografia/', 'BiografiaIndex', name='biografia'),
                   url(r'^contacto/', 'ContactoIndex', name='contacto'),
                   url(r'^biografia-cronologica/', 'BiografiaCronologicaIndex', name='biografia-cronologica'),
                   url(r'^biografia-narrativa/', 'BiografiaNarrativaIndex', name='biografia-narrativa'),
                   url(r'^servicios/', 'Servicios', name='servicios'),
                   url(r'^homenajes/', 'HomenajesIndex', name='homenajes'),
                   url(r'^legajados/', 'LegajadosIndex', name='legajados'),
                   url(r'^matrimonios/', 'MatrimonioIndex', name='matrimonios'),
                   url(r'^quince/', 'QuinceIndex', name='quince'),
                   url(r'^graduacion/', 'GraduacionIndex', name='graduacion'),
                   url(r'^fuerza-publica/', 'FuerzaPublicaIndex', name='fuerza-publica'),
                   url(r'^perfil/(?P<slug>[-\w\d]+)/$', 'PerfilPersona', name='perfil'),
                   url(r'^editar-homenaje/(?P<slug>[-\w]+)/(?P<id>\d+)/$', views.EditarHomenaje.as_view(), name='editar-homenaje'),
                   url(r'^origen_apellido/(?P<id>\d+)$', 'OrigenApell', name='origen_apellido'),
                   url(r'^fotos/(?P<id>\d+)$','Fotos', name='fotos'),
                   url(r'^ejercito/(?P<id>\d+)$','EjercitoIndex', name='ejercito'),
                   url(r'^reconocimientos/(?P<id>\d+)$','Reconocimientos', name='reconocimientos'),
                   url(r'^mishomenajes/','Mishomenajes', name='mishomenajes'),
                   url(r'^crear-homenaje$','CrearHomenaje',name='crear-homenaje'),
                   url(r'^search/', 'SearchIndex', name='search'),

                       )

sanjose_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from rest_framework import routers
from legado.views import PerfilViewSet , FotosPerfilViewSet

router = routers.DefaultRouter()
router.register(r'perfil',PerfilViewSet)

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'GranLegado.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('legado.urls')),
    (r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^accounts/profile/$', TemplateView.as_view(template_name='profile.html'),name="account_profile"),
    url(r'^accounts/', include('allauth.urls')),
    #url(r'^photologue/', include('photologue.urls', namespace='photologue')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legado/models.py
from django.contrib.auth.models import User
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill, ResizeToFit
from ckeditor.fields import RichTextField
from django.conf import settings
from audiofield.fields import AudioField
from django.template.defaultfilters import slugify
import os.path
from django.core import urlresolvers

class Perfil(models.Model):
    nombre = models.CharField(max_length=100,verbose_name='Nombre')
    usuario = models.ForeignKey(User)
    fecha_nacimiento = models.DateField(max_length=100,verbose_name='Fecha de nacimiento',blank=True,null=True)
    lugar_nacimiento = models.CharField(max_length=100,verbose_name='Lugar de Nacimiento',blank=True,null=True)
    imagen = ProcessedImageField(upload_to='perfiles/img',processors=[ResizeToFit(1200, 500)],format='JPEG',options={'quality': 50}, blank=True,null=True)
    profesion = models.CharField(max_length=100,verbose_name='Profesion',blank=True,null=True)
    biografia = RichTextField(verbose_name='Biografia',blank=True,null=True)
    origen_apellido = models.CharField(max_length=100,verbose_name='Origen del apellido',blank=True,null=True)
    qrcode = models.CharField(max_length=100,verbose_name='url del codigo QR',blank=True,null=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now=True)
    listo = models.BooleanField(default=True, verbose_name="Listo")
    publico = models.BooleanField(default=False, verbose_name="Publico")

    audio_file = AudioField(upload_to='perfiles/audio', blank=True,
                        ext_whitelist=(".mp3", ".wav", ".ogg"),
                        help_text=("Allowed type - .mp3, .wav, .ogg"))


    def audio_file_player(self):
        """audio player tag for admin"""
        if self.audio_file:
            file_url = settings.MEDIA_URL + str(self.audio_file)
            player_string = '<audio controls="controls"><source src="%s" /></audio> <p>%s</p>' % (file_url, os.path.basename(self.audio_file.name))
            return player_string

    audio_file_player.allow_tags = True
    audio_file_player.short_description = ('Audio file player')
    
    def save(self, *args, **kwargs):
        self.slug = slugify(str(self.nombre)+"-"+str(self.fecha_nacimiento))
        super(Perfil, self).save(*args, **kwargs)

        import requests
        urldata = "http://159.203.132.60/perfil/"+str(self.slug)
        url = "http://api.qrcode.unitag.fr/api?t_pwd=degraded&setting={%22EYES%22:{%22EYE_TYPE%22:%22LLLeft%22,%22COLOR_EHD%22:%228a9935%22,%22COLOR_IHD%22:%228a9935%22,%22COLOR_EBG%22:%2271801f%22,%22COLOR_IBG%22:%2271801f%22},%22BODY_TYPE%22:2,%22LAYOUT%22:{%22COLORBG%22:%22ffffff%22,%22GRADIENT_TYPE%22:%22HORI%22,%22COLOR1%22:%22afc928%22,%22COLOR2%22:%22d7eb67%22,%22FORCE_SHADOW%22:%22L%22,%22COLOR_SHADOW%22:%22b6b8a7%22}}&data={%22DATA%22:{%22URL%22:%22"+urldata+"%22},%22TYPE%22:%22URL%22}"
        r = requests.get(url)
        response = requests.get(url)
        if response.status_code == 200:
            furl = os.path.join(settings.MEDIA_ROOT, 'img/'+str(self.slug)+'.jpeg')
            f = open( furl , 'wb')
            f.write(response.content)
            f.close()
            self.qrcode = settings.MEDIA_URL+'img/'+str(self.slug)+'.jpeg'
            super(Perfil, self).save(*args, **kwargs)
    
    def qr_tag(self):
        """qr tag for admin"""
        if self.qrcode:
            file_url =  str(self.qrcode)
            url_string = '<img width="200px" src="'+file_url+'">'
            return url_string

    qr_tag.allow_tags = True
    qr_tag.short_description = ('Qr tag')
 
    def foto_perfil(self):
        if self.imagen:
            file_url =  settings.MEDIA_URL+str(self.imagen)
            url_string = '<img width="200px" src="'+file_url+'">'
            return url_string

    foto_perfil.allow_tags = True
    foto_perfil.short_description = ('Foto')

    def get_absolute_url(self):
        return urlresolvers.reverse('perfil', args=[self.slug,self.pk])
    def __unicode__(self):
        return str(self.nombre)


class FotosPerfil(models.Model):
    imagen = ProcessedImageField(upload_to='img/perfiles/otras',processors=[ResizeToFit(427, 285)],format='JPEG',options={'quality': 60})
    descripcion = models.CharField(max_length=100,verbose_name='Descripcion',blank=True,null=True)
    perfil =  models.ForeignKey(Perfil)
    def __unicode__(self):
        return self.descripcion

class FotosReconocimiento(models.Model):
    imagen = ProcessedImageField(upload_to='img/perfiles/reconocimiento',processors=[ResizeToFit(427, 285)],format='JPEG',options={'quality': 60})
    descripcion = models.CharField(max_length=100,verbose_name='Descripcion')
    perfil =  models.ForeignKey(Perfil)


class Servicio(models.Model):
    nombre = models.CharField(max_length=100,verbose_name='Nombre')
    imagen = ProcessedImageField(upload_to='img/servicios',processors=[ResizeToFit(427, 285)],format='JPEG',options={'quality': 60})
    resumen = RichTextField(verbose_name='Resumen')
    plan_amarillo = RichTextField(verbose_name='Plan Amarillo')
    plan_azul = RichTextField(verbose_name='Plan Azul')
    plan_rojo = RichTextField(verbose_name='Plan Rojo')
    """Los planes debe ser un Many to many a un Planes"""
    def miimagen(self):
        return settings.STATIC_URL+str(self.imagen)

    def __unicode__(self):
        return self.nombre

class Homenajes(models.Model):
    nombre = models.CharField(max_length=100,verbose_name='Nombre')
    imagen = ProcessedImageField(upload_to='img/homenajes',processors=[ResizeToFit(427, 285)],format='JPEG',options={'quality': 60})
    resumen = RichTextField(verbose_name='Resumen')
    parrafo_uno = RichTextField(verbose_name='Parrafo Primero')
    parrafo_dos = RichTextField(verbose_name='Parrafo Segundo')
    parrafo_tres = RichTextField(verbose_name='Parrafo Tercero')
    """Los PARRAFOS debe ser un Many to many a un MODEL"""
    def miimagen(self):
        return settings.STATIC_URL+str(self.imagen)


class Somos(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    parrafo_uno = RichTextField(verbose_name='Parrafo Primero')
    parrafo_dos = RichTextField(verbose_name='Parrafo Segundo')
    parrafo_tres = RichTextField(verbose_name='Parrafo Tercero')
    parrafo_cuatro = RichTextField(verbose_name='Parrafo Cuatro')
    """Los PARRAFOS debe ser un Many to many a un MODEL"""
    imagen = ProcessedImageField(upload_to='img/somos',processors=[ResizeToFit(1200, 551)],format='JPEG',options={'quality': 60})

class FuerzaMilitar(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    imagen = ProcessedImageField(upload_to='img/fuerzamilitar',processors=[ResizeToFit(427, 285)],format='JPEG',options={'quality': 60})
    body = RichTextField(verbose_name='Cuerpo')


class Legajados(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    resumen = RichTextField(verbose_name='Resumen')
    imagen = ProcessedImageField(upload_to='img/legajados',processors=[ResizeToFit(427, 285)],format='JPEG',options={'quality': 60})

    def miimagen(self):
        return settings.STATIC_URL+str(self.imagen)


class Funciona(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    parrafo_uno = RichTextField(verbose_name='Parrafo Primero')
    parrafo_dos = RichTextField(verbose_name='Parrafo Segundo')
    parrafo_tres = RichTextField(verbose_name='Parrafo Tercero')
    """Los PARRAFOS debe ser un Many to many a un MODEL"""
    imagen = ProcessedImageField(upload_to='img/somos',processors=[ResizeToFit(1200, 551)],format='JPEG',options={'quality': 60})


class PreguntasFrecuentes(models.Model):
    pregunta = models.CharField(max_length=100, verbose_name='Pregunta')
    respuesta = RichTextField( verbose_name='Respuesta')

    def __unicode__(self):
        return self.pregunta

class Biografia(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    texto = RichTextField(verbose_name='Texto')

    def __unicode__(self):
        return self.nombre

class BiografiaCronologica(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    texto = RichTextField(verbose_name='Texto')

    def __unicode__(self):
        return self.nombre

class BiografiaNarrativa(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    texto = RichTextField(verbose_name='Texto')

    def __unicode__(self):
        return self.nombre

class Direccion(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    calle = RichTextField(verbose_name='Calle')
    telefono = RichTextField(verbose_name='Telefono')
    movil = models.CharField(max_length=100, verbose_name='Movil')
    ubicacion = models.CharField(max_length=100, verbose_name='Ubicacion')

    def __unicode__(self):
        return self.nombre


class Matrimonio(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    resumen =RichTextField(verbose_name='Resumen')
    texto = RichTextField(verbose_name='Texto')
    imagen = ProcessedImageField(upload_to='img/matrimonio',processors=[ResizeToFit(427, 285)],format='JPEG',options={'quality': 60})

    def __unicode__(self):
        return self.nombre

class Quince(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    resumen =RichTextField(verbose_name='Resumen')
    texto = RichTextField(verbose_name='Texto')
    imagen = ProcessedImageField(upload_to='img/matrimonio',processors=[ResizeToFit(427, 285)],format='JPEG',options={'quality': 60})

    def __unicode__(self):
        return self.nombre


class Graduacion(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    resumen =RichTextField(verbose_name='Resumen')
    texto = RichTextField(verbose_name='Texto')

legado/forms.py
from django import forms
from django.forms import CheckboxInput
from haystack.forms import SearchForm
from .models import Perfil
from django import forms
from sanjose_project.settings import PALABRAS_INAPROPIADAS,EXPRESION_REGULAR_URL,MENSAJE_URLS
import re
from django.core.mail import send_mail
from django.forms.fields import FileField
from audiofield.widgets import CustomerAudioFileWidget

class PerfilSearchForm(SearchForm):

    def no_query_found(self):
        return self.searchqueryset.all()


class PerfilForm(forms.ModelForm):
    audio_file = forms.FileField(widget=CustomerAudioFileWidget)
    class Meta:
        model = Perfil
        fields = ['nombre','fecha_nacimiento','lugar_nacimiento','imagen','profesion','biografia','origen_apellido','audio_file','listo']

        widgets = {
            'listo': CheckboxInput(attrs={'hidden': 'hidden'})
            }

    def clean_biografia(self):
            biografia = self.cleaned_data['biografia']
            texto =str(biografia)
            urls = re.findall(EXPRESION_REGULAR_URL, texto)
            if urls.__len__() > 0:

                send_mail('Aqui va el asunto',MENSAJE_URLS, 'rmazahares@uci.cu',
                 ['rmazahares@uci.cu'], fail_silently=False)

                raise forms.ValidationError("Existe una url")
            for palabra in PALABRAS_INAPROPIADAS:
                if texto.find(palabra) > 0:
                    raise forms.ValidationError('Hay una mala palabra')

            return biografia

legado/templates/bio_cronologica.html
{%extends "base.html"%}

{% block Content %}
	<body class="no-sidebar">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header">

					<!-- Inner -->
						<div class="inner">
							<header>
								<h1>{%include "logo.html"%}</h1>
							</header>
						</div>

					<!-- Nav -->
					{% include 'menu.html' %}

				</div>

			<!-- Main -->
				<div class="wrapper style1">

					<div class="container">
						<article id="main" class="special">
							<header>
								<h2><a href="{% url "biografia-cronologica" %}">{{ bio_crono.nombre }}</a></h2>
								<p>

								</p>
							</header>
                            {% load static from staticfiles %}
							<!--<a href="#" class="image featured"><img src="{{ STATIC_URL }}{{ team.imagen }}" alt="" /></a>-->

							<section>
								<header>
									<h3>Biografia</h3>
								</header>
								<p>
									{{ bio_crono.texto  | safe }}
								</p>
							</section>
						</article>
						<hr />
						<div class="row">
							<article class="4u 12u(mobile) special">
								<a href="#" class="image featured"><img src="{% static "images/pic07.jpg" %}" alt="" /></a>
								<header>
									<h3><a href="#">Gravida aliquam penatibus</a></h3>
								</header>
								<p>
									{{ team.parrafo_cuatro  | safe }}
								</p>
							</article>
							<article class="4u 12u(mobile) special">
								<a href="#" class="image featured"><img src="{% static "images/pic08.jpg" %}" alt="" /></a>
								<header>
									<h3><a href="#">Sed quis rhoncus placerat</a></h3>
								</header>
								<p>
									Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
									porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
								</p>
							</article>
							<article class="4u 12u(mobile) special">
								<a href="#" class="image featured"><img src="{% static "images/pic09.jpg" %}" alt="" /></a>
								<header>
									<h3><a href="#">Magna laoreet et aliquam</a></h3>
								</header>
								<p>
									Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
									porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
								</p>
							</article>
						</div>
					</div>

				</div>



		</div>



	</body>
{% endblock Content %}

legado/templates/contacto.html
{%extends "base.html"%}

{% block Content %}
	<body class="no-sidebar">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header">

					<!-- Inner -->
						<div class="inner">
							<header>
								<h1>{%include "logo.html"%}</h1>
							</header>
						</div>

					<!-- Nav -->
					{% include 'menu.html' %}

				</div>

			<!-- Main -->
				<div class="wrapper style1">

					<div class="container">
						<article id="main" class="special">
							<header>
								<h2>{{direc.nombre }}</h2>

							</header>
                            {% load static from staticfiles %}
	
							<section>

								<p>
								Calle:{{ direc.calle  | safe }}
								</p>
                                <p>
								Telefono:{{ direc.telefono  | safe }}
								</p>
                                <p>
								Movil:{{ direc.movil  | safe }}
								</p>
                                <p>
								Ubicacion:{{ direc.ubicacion  | safe }}
								</p>

							</section>
						</article>
						<hr />
					<!-- Main -->
				<section id="main" class="container 75%">
					<header>
						<h2>Contactenos!</h2>
						<p>Debe contactarnos para brindarle nuestro servicio</p>
					</header>
					<div class="box">
						<form method="post" action="#">
							<div class="row uniform 50%">
								<div class="6u 12u(mobilep)">
									<input type="text" name="name" id="name" value="" placeholder="Nombre" />
								</div>
								<div class="6u 12u(mobilep)">
									<input type="email" name="email" id="email" value="" placeholder="Email" />
								</div>
                                <div class="6u 12u(mobilep)">
									<input type="text" name="name" id="name" value="" placeholder="Telefono contacto" />
								</div>
								<div class="6u 12u(mobilep)">
									<input type="email" name="email" id="email" value="" placeholder="Ciudad" />
								</div>
							</div>
							<div class="row uniform 50%">
								<div class="12u">
									<input type="text" name="subject" id="subject" value="" placeholder="Asunto" />
								</div>
							</div>
							<div class="row uniform 50%">
								<div class="12u">
									<textarea name="message" id="message" placeholder="Mensaje" rows="6"></textarea>
								</div>
							</div>
							<div class="row uniform">
								<div class="12u">
									<ul class="actions align-center">
										<li><input type="submit" value="Enviar" /></li>
									</ul>
								</div>
							</div>
						</form>
					</div>
				</section>
					</div>

				</div>



		</div>



	</body>
{% endblock Content %}

legado/templates/crear_homenaje.html
{%extends "base.html"%}

{% block Content %}
	<body class="no-sidebar">
		<div id="page-wrapper">
			<!-- Header -->
				<div id="header" >

					<!-- Inner -->
						<div class="inner">
							<header>
								<h1>{%include "logo.html"%}</h1>
							</header>
						</div>
					<!-- Nav -->
					{% include 'menu.html' %}
				</div>
			<!-- Main -->
				<div class="wrapper style1">

					<div class="container">
						<article id="main" class="special">
							<header>
								<h2><a href="{% url "homenajes" %}">{{ homenaj.nombre }}</a></h2>
								<p>
									{{ homenaj.resumen | safe }}
								</p>
							</header>
                         {% load static  from staticfiles %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
                 <form method="post" class="form" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}

                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% if field.label == "Listo" %}
                    <div class="6u 12u(narrower) slideThree" >
                   {{ field }}
                   <label for="id_listo"></label>

                   </div>
                   <label  for="copy">Marque si esta seguro que termino el homenaje</label>

                    {% else %}
                    {{ field }}

                    {% endif %}

                {% endfor %}
                <input type="submit" value="Guardar" />
            </form>



                            {% load static from staticfiles %}
							<!--<a href="#" class="image featured"><img src="{% static "images/pic06.jpg" %}" alt="" /></a>-->

						</article>
						<hr />

					</div>

				</div>

		</div>
	</body>
{% endblock Content %}

legado/templates/ejercito.html
{%extends "base.html"%}

{% block Content %}
	<body class="no-sidebar">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header" >

					<!-- Inner -->
						<div class="inner">
							<header>
								<h1>{%include "logo.html"%}</h1>
							</header>
						</div>

					<!-- Nav -->
					{% include 'menu.html' %}

				</div>

			<!-- Main -->
				<div class="wrapper style1">

					<div class="container">
						<article id="main" class="special">
							<header>
								<h2><a href="#">{{ ejer.nombre }}</a></h2>
								<p>
									{{ ejer.resumen | safe }}
								</p>
							</header>
                            {% load static from staticfiles %}
							<!--<a href="#" class="image featured"><img src="{% static "images/pic06.jpg" %}" alt="" /></a>-->

							<section>
								<!--<header>
									<h3>Ultrices tempor sagittis nisl</h3>
								</header>-->
								<p>
								{{ ejer.texto | safe  }}

								</p>

							</section>
                            <!--
							<section>
								<header>
									<h3>Augue euismod feugiat tempus</h3>
								</header>
								<p>

                                    ¿Le gustaría hacerle un homenaje muy especial, original, sobrio y, respetuoso a ese ser querido que tanto admira ó
                                    estima y que ése homenaje dure para siempre?
								</p>
                                <p>
                                    LEGADO: Aquello que se deja o transmite a los sucesores, sea cosa material o inmaterial. (RAE);
                                    por extensión se habla de legado a lo que se transmite de una generación a otra, ya sea de aptitudes,
                                    valores, historia, religión, costumbres, etcétera.
                                </p>
							</section>
							-->
						</article>
						<hr />

					</div>

				</div>



		</div>



	</body>
{% endblock Content %}

legado/templates/funciona.html
{%extends "base.html"%}

{% block Content %}
	<body class="no-sidebar">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header">

					<!-- Inner -->
						<div class="inner">
							<header>
								<h1>{%include "logo.html"%}</h1>
							</header>
						</div>

					<!-- Nav -->
					{% include 'menu.html' %}

				</div>

			<!-- Main -->
				<div class="wrapper style1">

					<div class="container">
						<article id="main" class="special">
							<header>
								<h2><a href="#">{{ func.nombre }}</a></h2>
								<p>

								</p>
							</header>
                            {% load static from staticfiles %}
							<a href="#" class="image featured"><img src="{{ STATIC_URL }}{{ func.imagen }}" alt="" /></a>
							<p>
								{{ func.parrafo_uno | safe  }}

							</p>
							<section>
								<header>
									<h3>VISIÓN:</h3>
								</header>
								<p>
									{{ func.parrafo_tres | safe  }}
								</p>

							</section>
							<section>
								<header>
									<h3>MISIÓN:</h3>
								</header>
								<p>
									{{ func.parrafo_dos  | safe }}
								</p>
							</section>
						</article>
						
					</div>

				</div>



		</div>



	</body>
{% endblock Content %}

legado/templates/graduacion.html
{%extends "base.html"%}

{% block Content %}
	<body class="no-sidebar">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header">

					<!-- Inner -->
						<div class="inner">
							<header>
								<h1>{%include "logo.html"%}</h1>
							</header>
						</div>

					<!-- Nav -->
					{% include 'menu.html' %}

				</div>

			<!-- Main -->
				<div class="wrapper style1">

					<div class="container">
						<article id="main" class="special">
							<header>
								<h2><a href="{% url 'graduacion' %}">{{ graduacion.nombre }}</a></h2>
								<p>
									Aqui puede ir una imagen o un texto!
								</p>
							</header>
                            {% load static from staticfiles %}
							<!--<a href="#" class="image featured"><img src="{% static "images/pic06.jpg" %}" alt="" /></a>-->
							<p>
								{{ graduacion.texto | safe }}
							</p>


						</article>
						<hr />

					</div>

				</div>



		</div>



	</body>
{% endblock Content %}

legado/templates/logo.html
<a href="{% url "inicio"  %}" id="logo"><img src="{{ STATIC_URL }}EGL-logo.png"></a>

legado/templates/somos.html
{%extends "base.html"%}

{% block Content %}
	<body class="no-sidebar">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header">

					<!-- Inner -->
						<div class="inner">
							<header>
								<h1>{%include "logo.html"%}</h1>
							</header>
						</div>

					<!-- Nav -->
					{% include 'menu.html' %}

				</div>

			<!-- Main -->
				<div class="wrapper style1">

					<div class="container">
						<article id="main" class="special">
							<header>
								<h2><a href="#">{{ team.nombre }}</a></h2>
								<p>

								</p>
							</header>
                            {% load static from staticfiles %}
							<a href="#" class="image featured"><img src="{{ STATIC_URL }}{{ team.imagen }}" alt="" /></a>
							<p>
								{{ team.parrafo_uno | safe  }}

							</p>
							<section>
								<header>
									<h3>VISIÓN:</h3>
								</header>
								<p>
									{{ team.parrafo_tres | safe  }}
								</p>

							</section>
							<section>
								<header>
									<h3>MISIÓN:</h3>
								</header>
								<p>
									{{ team.parrafo_dos  | safe }}
								</p>
							</section>
						</article>
						
					</div>

				</div>



		</div>



	</body>
{% endblock Content %}